/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.databasemidtermreq;

/**
 *
 * @author eronm
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

  String currentUsername;

    public Dashboard(String username) {
        initComponents();
        this.currentUsername = username; 
        this.setLocationRelativeTo(null); 
    }

    
    public Dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashboardWin = new javax.swing.JPanel();
        windowPane = new javax.swing.JPanel();
        controlwin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logoutButt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DashboardWin.setBackground(new java.awt.Color(245, 235, 220));
        DashboardWin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        DashboardWin.setPreferredSize(new java.awt.Dimension(400, 300));
        DashboardWin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        windowPane.setBackground(new java.awt.Color(110, 190, 180));
        windowPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        windowPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        controlwin.setBackground(new java.awt.Color(110, 190, 180));
        controlwin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        controlwin.setText("-           x");
        controlwin.setBorder(null);
        controlwin.addActionListener(this::controlwinActionPerformed);
        windowPane.add(controlwin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 80, 20));

        jLabel2.setFont(new java.awt.Font("Fixedsys Excelsior 3.01", 0, 14)); // NOI18N
        jLabel2.setText("ADMIN");
        windowPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        DashboardWin.add(windowPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 40));

        jPanel1.setBackground(new java.awt.Color(210, 210, 210));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pep big.png"))); // NOI18N

        logoutButt.setBackground(new java.awt.Color(210, 210, 210));
        logoutButt.setFont(new java.awt.Font("Fixedsys Excelsior 3.01", 0, 18)); // NOI18N
        logoutButt.setText("LOGOUT");
        logoutButt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutButt.addActionListener(this::logoutButtActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutButt)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(logoutButt)
                .addGap(18, 18, 18))
        );

        DashboardWin.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 110, 340));

        jPanel2.setBackground(new java.awt.Color(245, 235, 220));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        DashboardWin.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 460, 320));

        getContentPane().add(DashboardWin, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 33, 589, 377));

        Background.setBackground(new java.awt.Color(210, 230, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -30, 720, 470));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void controlwinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlwinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_controlwinActionPerformed

    private void logoutButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtActionPerformed
       
    new LogOut(currentUsername).setVisible(true);


    this.dispose();

    this.dispose();
    }//GEN-LAST:event_logoutButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel DashboardWin;
    private javax.swing.JButton controlwin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutButt;
    private javax.swing.JPanel windowPane;
    // End of variables declaration//GEN-END:variables
}
