/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.databasemidtermreq;

/**
 *
 * @author eronm
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginWindow = new javax.swing.JPanel();
        windowPane = new javax.swing.JPanel();
        controlwin = new javax.swing.JButton();
        LOGIN = new javax.swing.JLabel();
        usernameRegister = new javax.swing.JLabel();
        usernameRegField = new javax.swing.JTextField();
        PasswordReg = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        LoginBut = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginWindow.setBackground(new java.awt.Color(245, 235, 220));
        LoginWindow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        LoginWindow.setPreferredSize(new java.awt.Dimension(400, 300));
        LoginWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        windowPane.setBackground(new java.awt.Color(110, 190, 180));
        windowPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        windowPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        controlwin.setBackground(new java.awt.Color(110, 190, 180));
        controlwin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        controlwin.setText("-           x");
        controlwin.setBorder(null);
        controlwin.addActionListener(this::controlwinActionPerformed);
        windowPane.add(controlwin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 80, 20));

        LoginWindow.add(windowPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 40));

        LOGIN.setFont(new java.awt.Font("Fixedsys Excelsior 3.01", 1, 24)); // NOI18N
        LOGIN.setText("LOGIN");
        LoginWindow.add(LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        usernameRegister.setFont(new java.awt.Font("Fixedsys Excelsior 3.01", 0, 18)); // NOI18N
        usernameRegister.setText("Username");
        LoginWindow.add(usernameRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        usernameRegField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        usernameRegField.addActionListener(this::usernameRegFieldActionPerformed);
        LoginWindow.add(usernameRegField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 189, 40));

        PasswordReg.setFont(new java.awt.Font("Fixedsys Excelsior 3.01", 0, 18)); // NOI18N
        PasswordReg.setText("Password");
        LoginWindow.add(PasswordReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPasswordField1.addActionListener(this::jPasswordField1ActionPerformed);
        LoginWindow.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 189, 40));

        LoginBut.setBackground(new java.awt.Color(150, 220, 150));
        LoginBut.setFont(new java.awt.Font("Fixedsys Excelsior 3.01", 1, 24)); // NOI18N
        LoginBut.setText("LOGIN");
        LoginBut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LoginBut.addActionListener(this::LoginButActionPerformed);
        LoginWindow.add(LoginBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 120, 40));

        jButton1.setBackground(new java.awt.Color(245, 235, 220));
        jButton1.setFont(new java.awt.Font("Fixedsys Excelsior 3.01", 0, 12)); // NOI18N
        jButton1.setText("Don't have an account?");
        jButton1.setBorder(null);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        LoginWindow.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 150, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/retro.png"))); // NOI18N
        LoginWindow.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        getContentPane().add(LoginWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 590, 370));

        Background.setBackground(new java.awt.Color(210, 230, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -30, 720, 470));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -20, 670, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameRegFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameRegFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameRegFieldActionPerformed

    private void LoginButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void controlwinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlwinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_controlwinActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel LOGIN;
    private javax.swing.JButton LoginBut;
    private javax.swing.JPanel LoginWindow;
    private javax.swing.JLabel PasswordReg;
    private javax.swing.JButton controlwin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField usernameRegField;
    private javax.swing.JLabel usernameRegister;
    private javax.swing.JPanel windowPane;
    // End of variables declaration//GEN-END:variables
}
