/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.databasemidtermreq;

/**
 *
 * @author eronm
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class LogOut extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LogOut.class.getName());

   String userToProcess;

    // 2. The Custom Constructor (The Catcher's Mitt)
    public LogOut(String username) {
        initComponents();
        this.userToProcess = username;
        this.setLocationRelativeTo(null);
    }
    public LogOut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowPane = new javax.swing.JPanel();
        controlwin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Delete = new javax.swing.JButton();
        LoginAg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        windowPane.setBackground(new java.awt.Color(110, 190, 180));
        windowPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        windowPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        controlwin.setBackground(new java.awt.Color(110, 190, 180));
        controlwin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        controlwin.setText("-           x");
        controlwin.setBorder(null);
        controlwin.addActionListener(this::controlwinActionPerformed);
        windowPane.add(controlwin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 80, 20));

        jLabel2.setFont(new java.awt.Font("Fixedsys Excelsior 3.01", 0, 14)); // NOI18N
        jLabel2.setText("SESSION");
        windowPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 20));

        getContentPane().add(windowPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 40));

        jPanel2.setBackground(new java.awt.Color(195, 195, 195));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Delete.setText("DELETE ACCOUNT");
        Delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Delete.addActionListener(this::DeleteActionPerformed);
        jPanel2.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        LoginAg.setText("LOGIN");
        LoginAg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LoginAg.addActionListener(this::LoginAgActionPerformed);
        jPanel2.add(LoginAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Fixedsys Excelsior 3.01", 0, 14)); // NOI18N
        jLabel1.setText("What would you like to do next?");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 360, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void controlwinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlwinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_controlwinActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed

    String confirmName = JOptionPane.showInputDialog(this, 
        "WARNING: Deletion is permanent.\nType your username [" + userToProcess + "] to confirm:", 
        "Confirm Termination", 
        JOptionPane.WARNING_MESSAGE);

    if (confirmName == null || confirmName.trim().isEmpty()) {
        return; 
    }


    if (confirmName.equals(userToProcess)) {
        
        try {
            
            java.sql.Connection conn = DBConnection.connectDB();
            
         
            String sql = "DELETE FROM users WHERE username = ?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, userToProcess); 
            
            int rowsDeleted = pst.executeUpdate();
            
            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Account successfully deleted.");
                
                
                new Login().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error: Could not locate account in the mainframe.");
            }
            
            conn.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }

    } else {
        // 4. The Denial: They typed the wrong username
        JOptionPane.showMessageDialog(this, 
            " Username does not match.", 
            "Security Alert", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_DeleteActionPerformed

    private void LoginAgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginAgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginAgActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton LoginAg;
    private javax.swing.JButton controlwin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel windowPane;
    // End of variables declaration//GEN-END:variables
}
