/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.databasemidtermreq;

import javax.swing.JOptionPane;
public class Registration extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registration.class.getName());

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        RigesterWindow = new javax.swing.JPanel();
        windowPane = new javax.swing.JPanel();
        controlwin = new javax.swing.JButton();
        Register = new javax.swing.JLabel();
        NameRegister = new javax.swing.JLabel();
        nameRegField = new javax.swing.JTextField();
        usernameRegister = new javax.swing.JLabel();
        usernameRegField = new javax.swing.JTextField();
        PasswordReg = new javax.swing.JLabel();
        Passwordregf = new javax.swing.JPasswordField();
        EmailReg = new javax.swing.JLabel();
        emailRegF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RigesterWindow.setBackground(new java.awt.Color(245, 235, 220));
        RigesterWindow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        RigesterWindow.setPreferredSize(new java.awt.Dimension(400, 300));
        RigesterWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        windowPane.setBackground(new java.awt.Color(110, 190, 180));
        windowPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        windowPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        controlwin.setBackground(new java.awt.Color(110, 190, 180));
        controlwin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        controlwin.setText("-           x");
        controlwin.setBorder(null);
        controlwin.addActionListener(this::controlwinActionPerformed);
        windowPane.add(controlwin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 80, 20));

        RigesterWindow.add(windowPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 40));

        Register.setFont(new java.awt.Font("Retro Gaming", 0, 24)); // NOI18N
        Register.setText("Register");
        RigesterWindow.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        NameRegister.setFont(new java.awt.Font("Retro Gaming", 0, 18)); // NOI18N
        NameRegister.setText("Name");
        RigesterWindow.add(NameRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        nameRegField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nameRegField.addActionListener(this::nameRegFieldActionPerformed);
        RigesterWindow.add(nameRegField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 189, 30));

        usernameRegister.setFont(new java.awt.Font("Retro Gaming", 0, 14)); // NOI18N
        usernameRegister.setText("Username");
        RigesterWindow.add(usernameRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        usernameRegField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        usernameRegField.addActionListener(this::usernameRegFieldActionPerformed);
        RigesterWindow.add(usernameRegField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 189, 30));

        PasswordReg.setFont(new java.awt.Font("Retro Gaming", 0, 14)); // NOI18N
        PasswordReg.setText("Password");
        RigesterWindow.add(PasswordReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        Passwordregf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Passwordregf.addActionListener(this::PasswordregfActionPerformed);
        RigesterWindow.add(Passwordregf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 189, 30));

        EmailReg.setFont(new java.awt.Font("Retro Gaming", 0, 14)); // NOI18N
        EmailReg.setText("E-mail");
        RigesterWindow.add(EmailReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 50, 20));

        emailRegF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RigesterWindow.add(emailRegF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 190, 30));

        jButton1.setBackground(new java.awt.Color(150, 220, 150));
        jButton1.setFont(new java.awt.Font("Retro Gaming", 1, 18)); // NOI18N
        jButton1.setText("Register");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        RigesterWindow.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 120, 40));

        jButton2.setBackground(new java.awt.Color(245, 235, 220));
        jButton2.setFont(new java.awt.Font("Fixedsys Excelsior 3.01", 0, 12)); // NOI18N
        jButton2.setText("Already have an account?");
        jButton2.setBorder(null);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        RigesterWindow.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 150, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/envelope (1).png"))); // NOI18N
        RigesterWindow.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/retro.png"))); // NOI18N
        RigesterWindow.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/retro.png"))); // NOI18N
        RigesterWindow.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key (1).png"))); // NOI18N
        RigesterWindow.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        getContentPane().add(RigesterWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 590, 370));

        Background.setBackground(new java.awt.Color(210, 230, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -30, 720, 470));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -20, 670, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameRegFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameRegFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameRegFieldActionPerformed

    private void usernameRegFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameRegFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameRegFieldActionPerformed

    private void PasswordregfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordregfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordregfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

String name = nameRegField.getText();
String user = usernameRegField.getText();
String pass = String.valueOf(Passwordregf.getPassword());
String email = emailRegF.getText();


if (name.isEmpty() || user.isEmpty() || pass.isEmpty() || email.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill up all fields!", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

try {
    
    java.sql.Connection conn = DBConnection.connectDB();
    
    
    String sql = "INSERT INTO users (fullName, username, password, email) VALUES (?, ?, ?, ?)";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    
    pst.setString(1, name);
    pst.setString(2, user);
    pst.setString(3, pass);
    pst.setString(4, email);
    
   
    int updatedRows = pst.executeUpdate();
    if (updatedRows > 0) {
        JOptionPane.showMessageDialog(this, "Registration Successful!");
        
     
        new Login().setVisible(true);
        this.dispose();
    }
    
    conn.close();
    
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
}
    java.sql.Connection testConn = DBConnection.connectDB();
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void controlwinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlwinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_controlwinActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registration().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel EmailReg;
    private javax.swing.JLabel NameRegister;
    private javax.swing.JLabel PasswordReg;
    private javax.swing.JPasswordField Passwordregf;
    private javax.swing.JLabel Register;
    private javax.swing.JPanel RigesterWindow;
    private javax.swing.JButton controlwin;
    private javax.swing.JTextField emailRegF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameRegField;
    private javax.swing.JTextField usernameRegField;
    private javax.swing.JLabel usernameRegister;
    private javax.swing.JPanel windowPane;
    // End of variables declaration//GEN-END:variables
}
